benchmarket:
  name: 'tracey test' #human readable label for your environment
  username: 'john' #benchmarket user
  password: 'doe' #benchmarket password
  api_key: '9c572bf0-eca1-4247-8bef-d1df51d42239' #benchmarket key

#github:
#  token: '' #no token here - this is a public
#  secret: '' #our github secret, used for all endpoints

#job type with settings in the private folder

repos:

  #############################
  # performance tracker jobs
  #############################

  - owner: 'happner' #owner of repo
    name: 'tracey' #name, combined to form the full name tracey/happner
    testFolder: './test' #folder containing tests to be benchmarked
    node_js:
      - '7'
      - '0.10'
    job_type: 'performance-tracker-lite'
    schedule: '00 00 00 * * *'  # pattern: seconds | minute | hour | day of month | month | day of week

  - owner: 'happner'
    name: 'happner'
    testFolder: './test'
    node_js:
      - '7'
      - '0.10'
    job_type: 'performance-tracker-lite'
    schedule: '00 05 00 * * *'
    artifacts:
      folder: './artifacts/happner'
      index: 'artifact_hashes.txt'
      ipfs:
        host: '127.0.0.1'
        port: '5001'
      upload: true

  - owner: 'happner'
    name: 'happner-2'
    testFolder: './test'
    node_js:
      - '7'
      - '0.10'
    job_type: 'performance-tracker-lite'
    schedule: '00 10 00 * * *'
    artifacts:
      folder: './artifacts/happner-2'
      index: 'artifact_hashes.txt'
      ipfs:
        host: '127.0.0.1'
        port: '5001'
      upload: true

  - owner: 'happner'
    name: 'happn-3'
    testFolder: './test'
    node_js:
      - '7'
      - '0.10'
    job_type: 'performance-tracker-lite'
    schedule: '00 20 00 * * *'
    artifacts:
      folder: './artifacts/happn-3'
      index: 'artifact_hashes.txt'
      ipfs:
        host: '127.0.0.1'
        port: '5001'
      upload: true

  - owner: 'happner'
    name: 'thompson'
    testFolder: './test'
    node_js:
      - '7'
    job_type: 'performance-tracker-lite'
    schedule: '00 30 00 * * *'

  - owner: 'happner'
    name: 'happn'
    testFolder: './test'
    node_js:
      - '7'
      - '0.10'
    job_type: 'performance-tracker-lite'
    schedule: '00 40 00 * * *'
    artifacts:
      folder: './artifacts/happn'
      index: 'artifact_hashes.txt'
      ipfs:
        host: '127.0.0.1'
        port: '5001'
      upload: true

  - owner: 'happner'
    name: 'happner-cluster'
    testFolder: './test'
    node_js:
      - '7'
      - '0.10'
    job_type: 'performance-tracker-lite'
    schedule: '00 50 00 * * *'
    artifacts:
      folder: './artifacts/happner-cluster'
      index: 'artifact_hashes.txt'
      ipfs:
        host: '127.0.0.1'
        port: '5001'
      upload: true

  #############################
  # protocol documentation jobs
  #############################

  - owner: 'happner'
    name: 'happn-protocol'
    testFolder: './test'
    node_js:
      - '7'
      - '0.10'
    job_type: 'happn-protocol'
    schedule: '00 00 01 * * *'

  - owner: 'happner'
    name: 'happner-protocol'
    testFolder: './test'
    node_js:
      - '7'
      - '0.10'
    job_type: 'happner-protocol'
    schedule: '00 10 01 * * *'

job:
  folder: './tracey_job_folder' #where our jobs go to, in relation to index.js

notify:
  recipients: ['johndoe@missingperson.org'] #errors and speed reduction recipients
  threshold: 10 #percentage of decrease in overall speed to send out a warning email

queue:
    folder: './tracey_queue_folder' #where our queue is built, in relation to index.js

url: 'http://139.59.215.133:8080' #public url, that Tracey listens on, where our github hooks are sending their payloads to

